import type { ComponentType } from 'react'

import {
  ManagementGroups,
  Subscriptions,
  ResourceGroups,
  AllResources,
  Tags,
  Templates,
  Marketplace,
  Dashboard,
  AzureCloudShell,
  Powershell,
  RegionManagement,
  Reservations,
  AzureQuotas,
  ServiceHealth,
  AzureArc,
  AzureLighthouse,
  ResourceGraphExplorer,
  AzureDevOps,
} from '@threeveloper/azure-react-icons'

import {
  TenantProperties,
  Users,
  Groups,
  EnterpriseApplications,
  AppRegistrationsIdentity,
  ManagedIdentities,
  EntraIdentityRolesAndAdministratorsIdentity,
  EntraIdentityCustomRoles,
  ConditionalAccess,
  MultiFactorAuthentication,
  EntraPrivlegedIdentityManagement,
  IdentityGovernance,
  EntraDomainServices,
  AzureADB2C,
  ExternalIdentities,
  AdministrativeUnits,
  EntraIDProtection,
} from '@threeveloper/azure-react-icons'

import {
  VirtualMachine,
  VMScaleSets,
  AvailabilitySets,
  Disks,
  DisksSnapshots,
  AzureComputeGalleriesCompute,
  AppServicesCompute,
  AppServicePlansWeb,
  FunctionAppsCompute,
  KubernetesServicesCompute,
  ContainerInstancesCompute,
  ContainerRegistries,
  ContainerAppsEnvironments,
  AzureSpringAppsWeb,
} from '@threeveloper/azure-react-icons'

import {
  StorageAccounts,
  StorageContainer,
  BlobBlock,
  AzureFileshares,
  StorageQueue,
  Table,
  DataLakeStorageGen1,
  AzureNetAppFiles,
  DataBoxStorage,
  StorageExplorer,
  AzureStorageMover,
} from '@threeveloper/azure-react-icons'

import {
  VirtualNetworks,
  Subnet,
  NetworkInterfaces,
  NetworkSecurityGroups,
  ApplicationSecurityGroups,
  RouteTables,
  Firewalls,
  NAT,
  VirtualNetworkGateways,
  ExpressRouteCircuits,
  VirtualWANs,
  Connections,
  LoadBalancers,
  ApplicationGateways,
  FrontDoorAndCDNProfilesNetworking,
  CDNProfilesNetworking,
  TrafficManagerProfiles,
  DNSZones,
  DNSPrivateResolver,
  PrivateLink,
  PrivateEndpoints,
  PublicIPAddresses,
  Bastions,
  NetworkWatcherNetworking,
} from '@threeveloper/azure-react-icons'

import {
  AzureSQL,
  SQLDatabase,
  SQLManagedInstance,
  AzureSQLVM,
  SQLServer,
  SQLElasticPools,
  AzureCosmosDBDatabases,
  AzureDatabasePostgreSQLServer,
  AzureDatabaseMySQLServer,
  CacheRedis,
  AzureDatabaseMigrationServicesDatabases,
} from '@threeveloper/azure-react-icons'

import {
  AzureSynapseAnalyticsAnalytics,
  DataFactoriesAnalytics,
  AzureDatabricks,
  AzurePurviewAccounts,
  AzureDataExplorerClustersAnalytics,
  EventHubsAnalytics,
  StreamAnalyticsJobsAnalytics,
  PowerBIEmbedded,
} from '@threeveloper/azure-react-icons'

import {
  AzureServiceBus,
  EventGridTopics,
  EventGridSubscriptionsIntegration,
  LogicAppsIntegration,
  APIManagementServicesIntegration,
} from '@threeveloper/azure-react-icons'

import {
  KeyVaults,
  MicrosoftDefenderForCloud,
  AzureSentinel,
  AzureInformationProtectionSecurity,
  DiskEncryptionSets,
  DDoSProtectionPlans,
  WebApplicationFirewallPoliciesWAF,
} from '@threeveloper/azure-react-icons'

import {
  MonitorMonitor,
  Alerts,
  Workbooks,
  ApplicationInsightsMonitor,
  MetricsMonitor,
  ActivityLogMonitor,
  LogAnalyticsWorkspacesManagementGovernance,
  DiagnosticsSettingsMonitor,
  AzureManagedGrafana,
  Policy,
  Blueprints,
  Advisor,
  Compliance,
  CostManagement,
  CostAnalysis,
  CostBudgets,
  RecoveryServicesVaultsManagementGovernance,
  AzureBackupCenter,
  AutomationAccounts,
} from '@threeveloper/azure-react-icons'

export const AZURE_ICONS: Record<string, ComponentType<{ size?: string; viewBox?: string }>> = {
  managementgroup: ManagementGroups,
  subscription: Subscriptions,
  resourcegroup: ResourceGroups,
  allresources: AllResources,
  tags: Tags,
  template: Templates,
  marketplace: Marketplace,
  dashboard: Dashboard,
  cloudshell: AzureCloudShell,
  powershell: Powershell,
  region: RegionManagement,
  reservations: Reservations,
  quotas: AzureQuotas,
  servicehealth: ServiceHealth,
  arc: AzureArc,
  lighthouse: AzureLighthouse,
  resourcegraph: ResourceGraphExplorer,
  devops: AzureDevOps,
  tenant: TenantProperties,
  users: Users,
  groups: Groups,
  enterpriseapps: EnterpriseApplications,
  appregistration: AppRegistrationsIdentity,
  managedidentity: ManagedIdentities,
  roles: EntraIdentityRolesAndAdministratorsIdentity,
  customroles: EntraIdentityCustomRoles,
  conditionalaccess: ConditionalAccess,
  mfa: MultiFactorAuthentication,
  pim: EntraPrivlegedIdentityManagement,
  identitygovernance: IdentityGovernance,
  domainservices: EntraDomainServices,
  b2c: AzureADB2C,
  externalidentities: ExternalIdentities,
  adminunits: AdministrativeUnits,
  idprotection: EntraIDProtection,
  vm: VirtualMachine,
  vmss: VMScaleSets,
  availabilityset: AvailabilitySets,
  disk: Disks,
  snapshot: DisksSnapshots,
  gallery: AzureComputeGalleriesCompute,
  appservice: AppServicesCompute,
  appserviceplan: AppServicePlansWeb,
  functions: FunctionAppsCompute,
  aks: KubernetesServicesCompute,
  aci: ContainerInstancesCompute,
  acr: ContainerRegistries,
  containerapps: ContainerAppsEnvironments,
  springapps: AzureSpringAppsWeb,
  storage: StorageAccounts,
  blob: StorageContainer,
  blobblock: BlobBlock,
  files: AzureFileshares,
  queue: StorageQueue,
  storagetable: Table,
  adls: DataLakeStorageGen1,
  netapp: AzureNetAppFiles,
  databox: DataBoxStorage,
  storageexplorer: StorageExplorer,
  storagemover: AzureStorageMover,
  vnet: VirtualNetworks,
  subnet: Subnet,
  nic: NetworkInterfaces,
  nsg: NetworkSecurityGroups,
  asg: ApplicationSecurityGroups,
  routetable: RouteTables,
  firewall: Firewalls,
  natgateway: NAT,
  vnetgateway: VirtualNetworkGateways,
  expressroute: ExpressRouteCircuits,
  vwan: VirtualWANs,
  connection: Connections,
  loadbalancer: LoadBalancers,
  appgateway: ApplicationGateways,
  frontdoor: FrontDoorAndCDNProfilesNetworking,
  cdn: CDNProfilesNetworking,
  trafficmanager: TrafficManagerProfiles,
  dns: DNSZones,
  dnsresolver: DNSPrivateResolver,
  privatelink: PrivateLink,
  privateendpoint: PrivateEndpoints,
  publicip: PublicIPAddresses,
  bastion: Bastions,
  networkwatcher: NetworkWatcherNetworking,
  azuresql: AzureSQL,
  sqldatabase: SQLDatabase,
  sqlmi: SQLManagedInstance,
  sqlvm: AzureSQLVM,
  sqlserver: SQLServer,
  elasticpool: SQLElasticPools,
  cosmos: AzureCosmosDBDatabases,
  postgres: AzureDatabasePostgreSQLServer,
  mysql: AzureDatabaseMySQLServer,
  redis: CacheRedis,
  dbmigration: AzureDatabaseMigrationServicesDatabases,
  synapse: AzureSynapseAnalyticsAnalytics,
  datafactory: DataFactoriesAnalytics,
  databricks: AzureDatabricks,
  purview: AzurePurviewAccounts,
  dataexplorer: AzureDataExplorerClustersAnalytics,
  eventhubs: EventHubsAnalytics,
  streamanalytics: StreamAnalyticsJobsAnalytics,
  powerbi: PowerBIEmbedded,
  servicebus: AzureServiceBus,
  eventgrid: EventGridTopics,
  eventgridsub: EventGridSubscriptionsIntegration,
  logicapps: LogicAppsIntegration,
  apim: APIManagementServicesIntegration,
  keyvault: KeyVaults,
  defender: MicrosoftDefenderForCloud,
  sentinel: AzureSentinel,
  infoprotection: AzureInformationProtectionSecurity,
  diskencryption: DiskEncryptionSets,
  ddos: DDoSProtectionPlans,
  wafpolicy: WebApplicationFirewallPoliciesWAF,
  monitor: MonitorMonitor,
  alerts: Alerts,
  workbooks: Workbooks,
  appinsights: ApplicationInsightsMonitor,
  metrics: MetricsMonitor,
  activitylog: ActivityLogMonitor,
  loganalytics: LogAnalyticsWorkspacesManagementGovernance,
  diagnostics: DiagnosticsSettingsMonitor,
  grafana: AzureManagedGrafana,
  policy: Policy,
  blueprints: Blueprints,
  advisor: Advisor,
  compliance: Compliance,
  cost: CostManagement,
  costanalysis: CostAnalysis,
  costbudgets: CostBudgets,
  recoveryvault: RecoveryServicesVaultsManagementGovernance,
  backupcenter: AzureBackupCenter,
  automation: AutomationAccounts,
}
