import {
  Workflow, Box, Cog, MemoryStick, Zap, Brain, Waves, Share2,
  Filter, Copy, Table2,
  Monitor, Terminal, Code2, FileCode2, Cloud, Building2, Braces,
  Cpu, Layers, Globe, Database, Network, Wrench,
  Receipt, Tag, Gauge, BellRing,
  KeyRound, ShieldCheck, UserCheck, ScanFace, ScrollText, GitBranch,
  Ban, CircleCheck, CircleSlash,
  Router, DoorOpen, Server, Boxes,
  Clock, Repeat, Lock, Scale,
  HardDrive, Folder, FileText, Users, Power, Plug, Scissors, Link, Skull,
  Search, Pencil, Sigma, Hash, ArrowUpDown, Regex, Bug,
  BarChart3, ChartPie, Star, Snowflake, CalendarDays, Ruler, History, GitMerge,
  Warehouse, Package, ArrowDownUp, Trash2, ListTree, Fingerprint,
  type LucideIcon,
} from 'lucide-react'

export const LUCIDE_ICONS: Record<string, LucideIcon> = {
  monitor: Monitor,
  terminal: Terminal,
  code: Code2,
  filecode: FileCode2,
  cloud: Cloud,
  building: Building2,
  braces: Braces,
  cpu: Cpu,
  layers: Layers,
  globe: Globe,
  database: Database,
  network: Network,
  wrench: Wrench,
  receipt: Receipt,
  tag: Tag,
  gauge: Gauge,
  bell: BellRing,
  key: KeyRound,
  shieldcheck: ShieldCheck,
  usercheck: UserCheck,
  scanface: ScanFace,
  scroll: ScrollText,
  gitbranch: GitBranch,
  ban: Ban,
  circlecheck: CircleCheck,
  circleslash: CircleSlash,
  router: Router,
  dooropen: DoorOpen,
  server: Server,
  boxes: Boxes,
  clock: Clock,
  repeat: Repeat,
  lock: Lock,
  scale: Scale,

  workflow: Workflow,
  box: Box,
  gears: Cog,
  memory: MemoryStick,
  zap: Zap,
  brain: Brain,
  waves: Waves,
  share: Share2,
  funnel: Filter,
  copy: Copy,
  table: Table2,
  harddrive: HardDrive,
  folder: Folder,
  file: FileText,
  users: Users,
  power: Power,
  plug: Plug,
  scissors: Scissors,
  link: Link,
  skull: Skull,
  search: Search,
  pencil: Pencil,
  sigma: Sigma,
  hash: Hash,
  sortarrows: ArrowUpDown,
  regex: Regex,
  bug: Bug,
  barchart: BarChart3,
  chartpie: ChartPie,
  star: Star,
  snowflake: Snowflake,
  calendar: CalendarDays,
  ruler: Ruler,
  history: History,
  merge: GitMerge,
  warehouse: Warehouse,
  package: Package,
  swap: ArrowDownUp,
  trash: Trash2,
  tree: ListTree,
  fingerprint: Fingerprint,
}
